version: '3.9'

services:
  agremate-api:
    build:
      context: .
      dockerfile: Agremate/Dockerfile
    container_name: agremate-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=agremate_db;Username=postgres;Password=Postgre@Db900

  postgres:
    image: postgres:latest
    container_name: agremate-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgre@Db900
      POSTGRES_DB: agremate_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
